#ifndef BOARD_BTNCONTROLLER_CONFIG_H
#define BOARD_BTNCONTROLLER_CONFIG_H

/**
 * Do NOT edit this file!
 *
 * This is the default BtnController config file.
 * You may provide your own implementation at project level.
 *
 * For this:
 * - Copy/paste this file into a folder named 'config' in
 *   you projects include/source directory.
 * - Add a compiler include path so that your file is seen
 *   before the default config file provided in the platform
 *   package.
 * - Adjust the content of your config file to your needs.
 * - Remove this comment in your config file.
 */

#define BTNCONTROLLER_TRACE_ENABLE      0

#endif // BOARD_BTNCONTROLLER_CONFIG_H
